import os
import random
from PIL import Image, ImageDraw, ImageOps # Using Pillow for image manipulation
import datetime
import time

# --- Constants ---
OUTPUT_DIR = "byterot_artifacts"
MOCK_API_RESPONSE_TIME = 0.5 # Simulate AI processing time
MOCK_PRICE = 1.0

def apply_glitch_effect(input_image_path: str, output_image_path: str, glitch_intensity: int = 15):
    """
    Applies a retro digital decay/glitch effect to an image using Pillow.
    Effects include pixel shifting and color channel disruption.
    """
    try:
        with Image.open(input_image_path).convert("RGB") as img:
            width, height = img.size
            pixels = img.load()

            # Randomly shift blocks of pixels horizontally
            for _ in range(int(height * 0.1)): # Apply glitch to 10% of lines
                y = random.randint(0, height - 1)
                shift = random.randint(-glitch_intensity, glitch_intensity)
                if shift != 0:
                    # Shift pixels in a line
                    temp_line = [pixels[x, y] for x in range(width)]
                    for x in range(width):
                        shifted_x = (x + shift) % width
                        pixels[shifted_x, y] = temp_line[x]

            # Introduce color channel separation/noise in random areas
            for _ in range(int(width * height * 0.005)): # Affect 0.5% of pixels
                x, y = random.randint(0, width - 1), random.randint(0, height - 1)
                r, g, b = pixels[x, y]

                # Randomly shift one color channel slightly
                channel_to_shift = random.choice(['r', 'g', 'b'])
                shift_amount = random.randint(-glitch_intensity // 5, glitch_intensity // 5)

                if channel_to_shift == 'r':
                    r = max(0, min(255, r + shift_amount))
                elif channel_to_shift == 'g':
                    g = max(0, min(255, g + shift_amount))
                else: # 'b'
                    b = max(0, min(255, b + shift_amount))
                pixels[x, y] = (r, g, b)

            # Add a subtle "scanline" or "CRT" overlay (simplified)
            draw = ImageDraw.Draw(img)
            for y in range(0, height, 2):
                draw.line((0, y, width, y), fill=(0, 0, 0, 30)) # Transparent black lines

            img.save(output_image_path)
        print(f"✅ Generated ByteRot Bloom artifact: {os.path.basename(output_image_path)}")
        return True
    except FileNotFoundError:
        print(f"❌ Error: Input image '{input_image_path}' not found.")
        return False
    except Exception as e:
        print(f"❌ An error occurred during image processing: {e}")
        return False

def generate_mock_image(filename="sample_input.png"):
    """Generates a simple mock image for testing if no input is provided."""
    if os.path.exists(filename):
        print(f"ℹ️ Using existing mock image: {filename}")
        return filename
    try:
        img = Image.new('RGB', (256, 192), color = (70, 130, 180)) # Steel Blue
        draw = ImageDraw.Draw(img)
        # Add some random shapes/text to make it look like a "user image"
        draw.ellipse((50, 20, 150, 120), fill=(255, 200, 0), outline=(255, 0, 0)) # Yellow circle
        draw.polygon([(180, 50), (220, 20), (240, 90), (160, 100)], fill=(0, 200, 50)) # Green polygon
        draw.text((10, 150), "ByteRot Bloom", fill=(255, 255, 255))
        img.save(filename)
        print(f"⚙️ Created a sample image for you: {filename}")
        return filename
    except Exception as e:
        print(f"❌ Could not create mock image: {e}")
        return None

def display_retro_ui_message(message: str):
    """Prints a message in a retro, pixel-art style (simulated)."""
    border = "█" * (len(message) + 4)
    print(f"\\n{border}\\n█ {message} █\\n{border}\\n")

def main():
    display_retro_ui_message("W E L C O M E  T O  B Y T E R O T  B L O O M")
    print("✨ Relive the glorious digital decay of the 90s! ✨")
    print(f"Your unique digital artifact will be saved in: '{OUTPUT_DIR}'")

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        print(f"📂 Created output directory: '{OUTPUT_DIR}'")

    input_path = input(">>> Enter path to your image file (e.g., my_photo.jpg) or leave blank for a sample: ").strip()

    if not input_path:
        input_path = generate_mock_image()
        if not input_path:
            print("🛑 Exiting: Could not prepare a sample image.")
            return

    if not os.path.exists(input_path):
        print(f"❌ Error: The specified input image '{input_path}' does not exist.")
        print("Please ensure the path is correct or try again with a sample image.")
        return

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_filename = f"byterot_bloom_{timestamp}.png"
    output_full_path = os.path.join(OUTPUT_DIR, output_filename)

    print(f"🤖 Otto is processing '{os.path.basename(input_path)}' with digital decay magic... (simulated AI delay: {MOCK_API_RESPONSE_TIME}s)")
    # Simulate AI processing time
    time.sleep(MOCK_API_RESPONSE_TIME)

    success = apply_glitch_effect(input_path, output_full_path)

    if success:
        print(f"\\n✨ Your 'ByteRot Bloom' masterpiece is ready! Preview at: {output_full_path}")
        print(f"💰 This unique digital artifact can be yours for just ${MOCK_PRICE:.2f}!")
        buy_choice = input(">>> Do you wish to 'purchase' this artifact? (yes/no): ").strip().lower()

        if buy_choice == 'yes':
            print("💳 Transaction simulated! Thank you for your 'purchase' of digital decay art!")
            print(f"💾 Your artifact '{os.path.basename(output_full_path)}' is now officially 'yours'.")
        else:
            print("💔 Understood. Your artifact has been generated but not 'purchased'.")

    display_retro_ui_message("T H A N K S  F O R  U S I N G  B Y T E R O T")
    print(f"💡 Tip: Run this script daily to discover new decay patterns on your images!")
    print("       You can schedule this with cron (Linux/macOS) or Task Scheduler (Windows).")
    print("       Example for cron: 0 0 * * * python /path/to/byterot_bloom.py > /dev/null 2>&1")

if __name__ == "__main__":
    main()